export enum ErrorType {
  Period = "Period",
  Participants = "Participants",
  Date = "Date",
  Area = "Area",
  TimeSlot = "TimeSlot",
  Firstname = "Firstname",
  Lastname = "Lastname",
  Email = "Email",
  PhoneNumber = "PhoneNumber",
  Comment = "Comment",
  TermsConditions = "TermsConditions",
  ReservationNotAvailable = "ReservationNotAvailable",
  Company = "Company",
  Newsletter = "Newsletter",
}
